addr: :8765
miniflux: http://miniflux:8080
minio:
  endpoint: minio.onlyquant.top
  accessKeyID: dashboardtest
  bucket: journal
  secure: true
  expiry: 160h
route:
  back:
    base: "/api"
  front:
    dir: "client/dist"
    index: "client/dist/index.html"
  journal:
    dir: "client/journal"
    index: "client/journal/journal.html"
db:
  name: dashboard_test
  host: localhost
  port: 5432
  username: onlyquant
